plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.gtasgntrj.launcher'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.gtasgntrj.launcher'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
